do local _ = {
  about_text = "",
  disabled_channels = {},
  enabled_plugins = {
    "onservice",
    "tagall",
    "inrealm",
    "ingroup",
    "inpm",
    "banhammer",
    "stats",
    "anti_spam",
    "owners",
    "arabic_lock",
    "save",
    "get",
    "broadcast",
    "download_media",
    "invite",
    "all",
    "leave_ban",
    "admin",
    "plugins",
    "admin",
    "calc",
    "copyright",
    "dl",
    "up",
    "echo",
    "echoset",
    "echoget",
    "feedback",
    "filtering",
    "getplug",
    "google",
    "help",
    "id",
    "info",
    "lock_ads",
    "lock_badword",
    "lock_chat",
    "lock_eng",
    "lock_sticker",
    "lock_tag",
    "me",
    "plugins",
    "qrcode",
    "share",
    "tex",
    "version",
    "welcome"
  },
  help_text = "",
  moderation = {
    data = "data/moderation.json"
  },
  sudo_users = {
    81578020,
	129315952,
	185574862
  }
}
return _
end